Repository statisticsnorway/ssb-altinn-python, pull requests merged in 2024-02, with the labels that each got.

#313 Pub85 vst
  README.md
  src/altinn/flatten.py
  tests/test_flatten.py
Labels: bug, documentation

#317 Release 0.4.2
  pyproject.toml
Labels: documentation, python, refactoring

#320 Release 0.4.3
  pyproject.toml
Labels: documentation, enhancement, python

#322 Release 0.4.4
  pyproject.toml
Labels: bug, python, testing

#324 Release 0.4.5
  pyproject.toml
Labels: enhancement, python

#326 Release 0.4.6
  pyproject.toml
Labels: bug
